#/*# 应用名称
#spring.application.name=blog
## 应用服务 WEB 访问端口
#server.port=8080
## 数据库驱动：
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## 数据源名称
#spring.datasource.name=defaultDataSource
## 数据库连接地址
#spring.datasource.url=jdbc:mysql://localhost:3306/bubble?serverTimezone=GMT
## 数据库用户名&密码：
#spring.datasource.username=root
#spring.datasource.password=root

server:
  port: 8080   # 应用服务 WEB 访问端口

max-http-header-size: 4048576
tomcat:
  max-http-post-size: -1  #请求参数长度

spring:
  application:
    name: weibo  # 应用名称
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # 数据库驱动：
    url: jdbc:mysql://localhost:3306/weibo?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8  #数据库名称
    username: root
    password: root
  jpa:
    show-sql: true  #显示sql语句在一行
    properties:
      hibernate:
        format_sql: true #使看到的sql语句格式化
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB  #单个文件的最大上限
      max-request-size: 1000MB #单个请求的文件总大小上限

###图片上传配置
upload:
  #静态资源对外暴露的访问路径 一个* 代表只匹配该路径下的一级子路径
  staticAccessPath: /blogImages/*

